### ISSUE TITLE
Support home switch inputs

### ISSUE THREAD

**Issue by madcowswe** [odriverobotics/ODrive#109]
Add input with configurable polarity for home switch.
Add a go-home command, that takes as a parameter a homing-speed.
This should go with constant speed in the direction specified by signed velocity, until home switch is triggered. At that point set the current position (via offset or otherwise) to 0, without breaking commutation.

**Comment by Wetmelon** [comment]
Task List
- [x] Add hardware support
- [x] Add callbacks
- [x] Homing function
- [x] Homing speed limit
- [x] Fault on endstop pressed flag

**Comment by Wetmelon** [comment]
Merged into RC & devel
