### ISSUE TITLE
Preflashed firmware compatibility

### ISSUE THREAD

**Issue by madcowswe** [odriverobotics/ODrive#130]
- [x] Check that Boot0 will in fact put the device into DFU mode
- [x] Expose Boot0 on hardware v3.5
- [x] Flatten UUID to serial number same as DFU.

**Comment by samuelsadok** [comment]
The DFU mode can in fact be invoked by connecting BOOT0 to 3.3V and connecting BOOT1 (aka GPIO 1) to GND. In my tests the DFU mode was entered even when BOOT1 was floating.
Also:
 * [x] look up OTP-memory capabilities so we can burn the board version into OTP
