### ISSUE TITLE
Count step/dir in encoder TIM hardware

### ISSUE THREAD

**Issue by madcowswe** [odriverobotics/ODrive#135]
Crinq says:
Input 1/2 as per https://github.com/rene-dev/stmbl/blob/v0.9.18/src/comps/enc_cmd.c#L138-L160
Check reference manual for input capture and Encoder mode.

**Comment by madcowswe** [comment]
Crinq [on discord](https://discordapp.com/channels/369667319280173067/369678848972816385/780826205443063819):
```
CR1:
  CEN = 1
CCER:
  CC1E = 1
  CC1P = 1
  CC2E = 1
SMCR: 
  SMS = 3
CCMR1:
  CC1S = 2
  CC2S = 1
ARR = XYZ
```

**Comment by madcowswe** [comment]
Some more info here:
https://stackoverflow.com/questions/32947972/stm32-how-to-make-pulse-count-up-down-with-timer

Critical note:
> The TIM would still act as a step and direction counter BUT would count in different directions for the same input level on the direction pin between bootups.

We should validate both the stmbl variant, and the stackoverflow variant.

**Comment by madcowswe** [comment]
Crinq says this code https://github.com/rene-dev/stmbl/blob/master/src/comps/enc_cmd.c#L140-L161
to ignore the comments they are out of date.
Also:
> step signal is tim2_ch1, dir is tim2_ch2

**Comment by Wetmelon** [comment]
Wontfix.  We improved the overhead associated with software interrupts and incrementing the step/dir, to now support up to 250kHz on a channel.
