### ISSUE TITLE
Initial Endpoint documenation

### ISSUE THREAD

**Issue by sevenbitbyte** [odriverobotics/ODrive#157]
Please document the varios endpoints and their expected behaviors. The existing [protocol documentation is excellent](https://github.com/madcowswe/ODrive/blob/master/Firmware/protocol.md) but doesn't cover what endpoints to expect or how they work.

Most endpoints appear to be implemented [here in the firmware](https://github.com/madcowswe/ODrive/blob/master/Firmware/MotorControl/commands.cpp#L120)

**Comment by madcowswe** [comment]
Yes we should add some documentation indeed, and we will be working on that [here](http://docs.odriverobotics.com/commands). This pertains to the firmware version 4.0 and later, which is currently under construction, preview [here](https://github.com/madcowswe/ODrive/tree/sam_refactoring). One thing in particular to note with this refactoring is that the endpoints are now declared within each object, example [here](https://github.com/madcowswe/ODrive/blob/sam_refactoring/Firmware/MotorControl/axis.hpp#L167)

**Comment by madcowswe** [comment]
With v0.5.1 endpoints can now be directly documented in the `odrive-interface.yaml`. Some initial documentation has been done.
