### ISSUE TITLE
Threads cleanup

### ISSUE THREAD

**Issue by madcowswe** [odriverobotics/ODrive#171]
## Init thread
The init of all the objects run on an init thread. This is silly, and was added by Cube to initalize the USB in the background. For us it's better to have the full main stack for init, especially because the fibre tree is huge.
We should run all init on the main thread before the scheduler starts, and get rid of the init task.

## Application thread
Some application logic is suited for running directly on the ODrive. We should make an application thread with an example demo program, and add some example IO parameters.

## Documentation
We should have all threads and their priorities, stack size, and description listed in a central location, to give devs an easy overview of what's running on the ODrive

**Comment by madcowswe** [comment]
Notes on App thread:
You can add it in the bottom of main.cpp. Can you make the official skeleton version that just has a dummy stub for people to add their application code in? Like this:
```
run_application() {
// Put your application code here

// Currently this does nothing
osDelay(100);
}
```
you can start it at the bottom of odrive_main (in main.cpp)
```
osThreadDef(application_thread, run_application, osPriorityLow, 0, 4096);
app_thread_id= osThreadCreate(osThread(application_thread), NULL);
```

Add to the top area of main.cpp
```
osThreadId app_thead_id;
```
and in vApplicationIdleHook add the appropriate entry using app_thead_id. You will probably need to extend the system_stats_ struct.

**Comment by Wetmelon** [comment]
Did #318 take care of this, or just the initialization?  

List of threads [on Google Drive](https://docs.google.com/spreadsheets/d/1Q7qS4xY7szme8t-sMSE4pxSfSi8XxtwAaxu0Tp91lds/edit#gid=2115225907)

**Comment by Wetmelon** [comment]
#472 makes large changes.  @samuelsadok we should consider adding the documentation as requested above

**Comment by samuelsadok** [comment]
I started a simple list here: https://github.com/madcowswe/ODrive/blob/control-loop-refactor/docs/resources.md
