### ISSUE TITLE
"Oh no odrv0 disappeared" message on Mac after a few seconds

### ISSUE THREAD

**Issue by Deezmaker** [odriverobotics/ODrive#173]
When running "odrivetools" I get the usual message "Connected to ODrive as odrv0" after a few seconds of start up. Then after about 5-10 seconds later I get "Oh no odrv0 disappeared" message and nothing works.

oDrive board: 3.5
Firmware: 0.4.1-dev
MacOs 10.12.6 (Sierra)

**Comment by Nate711** [comment]
I'm having the same problem. Running High Sierra 10.13.4

**Comment by samuelsadok** [comment]
Fixed in #178

**Comment by madcowswe** [comment]
Released hotfix on odrive-0.4.0.post4.
To upgrade to the fixed version please run `pip install odrive --upgrade --no-cache-dir`
