### ISSUE TITLE
Reliability issues on ASCII protocol on USB

### ISSUE THREAD

**Issue by madcowswe** [odriverobotics/ODrive#207]
Sending position commands at a high rate stalls after some time. See [original thread](https://discourse.odriverobotics.com/t/ascii-commands-makes-odrive-unreachable/849), which includes a test program for windows.

**Comment by madcowswe** [comment]
Problems also reported in [this thread](https://discourse.odriverobotics.com/t/serial-timeout-issue/1039).

**Comment by rklosinski** [comment]
I have the same problem. Hangs with multiple serial commands. How close is this to being corrected?

**Comment by 27183** [comment]
We are running the binary protocol and having some commands contain embedded bytes that can be interpreted as valid ASCII commands; which are not intended and do damage.

**Comment by Wetmelon** [comment]
Closing until we hear anything new from 0.5.3.
