### ISSUE TITLE
support for Silabs EFM8BB2

### ISSUE THREAD

**Issue by papage** [odriverobotics/ODrive#21]
Hi Oskar and all,

I think it would be useful, sometime in the future, to software support Silabs EFM8BB2 (and other) family of CPUs. The case is that this CPU is used for many ESCs for copters that now run bheli firmware and all these ESCs can be reprogrammed with your firmware! For example, DYS XSD 30A is such ESC (about 15USD on banggood). This means that there will be plenty cheap hardware from various manufacturers that will be able to drive any brushless motor for robotics. The immediate availability of the HW, will greatly accelerate the development of this project!

Thanks for the great project!
Spiros

**Comment by madcowswe** [comment]
Hey papage, thanks for your input.
I think the class of 8-bit processors commonly used on hobby ESC's don't really have the computational power required to run the algorithms I am using for the ODrive.
Also, I run FOC control, which requires phase current feedback sensors. I don't think I have seen any ESC's that have that kind of hardware.

Nevertheless, thanks for the tip!
