### ISSUE TITLE
Move wiki content to new docs

### ISSUE THREAD

**Issue by 100gamma** [odriverobotics/ODrive#215]
The [tuning procedure link](https://github.com/madcowswe/ODrive/blob/master/Firmware/README.md#tuning-parameters) on the [main wiki page](https://github.com/madcowswe/ODrive/wiki) appears to be broken.

**Comment by madcowswe** [comment]
Thanks for the heads up. Actually that wiki page isn't maintained anymore, and we will be looking to move the relevant content to the [docs](http://docs.odriverobotics.com).

**Comment by Capo01** [comment]
I have pulled and updated the still relevant parts from the wiki and added known solutions to some of the errors I have encountered. https://github.com/madcowswe/ODrive/pull/239

**Comment by madcowswe** [comment]
Done
