### ISSUE TITLE
Incremental / circular position control mode.

### ISSUE THREAD

**Issue by madcowswe** [odriverobotics/ODrive#226]
Allow the motor to be incrementally advanced forever in a incremental / circular control mode.
This should allow continuous spinning in step/dir input mode.

**Comment by madcowswe** [comment]
Note that instead of a fixed circular space, we could do a "reference shift on demand", as I described [here](https://discourse.odriverobotics.com/t/incremental-movement-in-position-mode/1167/5?u=madcowswe)

**Comment by Wetmelon** [comment]
I believe this is ALMOST working if you use cpr mode, except shadow count will eventually roll over?

**Comment by samuelsadok** [comment]
This is actually implemented since firmware v0.4.7.
A rollover of shadow_count shouldn't pose any issue since it's only used to calculate the delta between two encoder updates.
