### ISSUE TITLE
compile error please help 

### ISSUE THREAD

**Issue by masterchen** [odriverobotics/ODrive#229]
with latest version , after running 'make' command under firmware folder,error happens:
dell@DESKTOP-72260OA MINGW64 /e/E/github/ODriver/ODrive.git/trunk/Firmware
$ make
 100% 1) updated variant: tup.config
 *** tup errors ***
 *** Command ID=499 failed with return value -1073741819
tup error: Expected to write to file 'build/version.h' from cmd 499 but didn't
 *** tup: 1 job failed.
make: *** [all] Error 1

**Comment by Capo01** [comment]
Hi masterchen 

You may not get any responses on here since this is really for issues with the firmware while your issue sounds like a problem with your configuration setup. I recommend starting a new thread on [the odrive forums](https://discourse.odriverobotics.com).
