### ISSUE TITLE
0-100 PWM Input Mode

### ISSUE THREAD

**Issue by abickel** [odriverobotics/ODrive#230]
Please create a PWM motor control function (0 to 100% duty cycle).
My specific application is spindle motor for a CNC Mill and the motion controller (Ethernet Smooth Stepper) outputs a 0~100% duty cycle at a user specified frequency.  In addition, the ODrive needs to accept a motor direction input (single pin).

Many thanks.

**Comment by Wetmelon** [comment]
Per https://discourse.odriverobotics.com/t/velocity-control-using-pwm-input/1063/7

**Comment by madcowswe** [comment]
Also known common mode:
* "0 to 100" -> "0 to max"
* "0 50 100" -> "-max 0 +max"

**Comment by robsonswiss** [comment]
Just to clarify, "0 to 100" goes with a direction input as well.

**Comment by Wetmelon** [comment]
Won't add, but we accept well-tested PRs.
