### ISSUE TITLE
Timeout parameter for controlling through interfaces

### ISSUE THREAD

**Issue by woofer46** [odriverobotics/ODrive#249]
If Odrive is controlling by some stuff for velocity (robot platform) through digital interface (UART, CAN), it is necessary to have timeout in odrive FW, because if link will be lost, odrive will continue to run motor with last target speed.
parameter for example:
odrv0.axis0.stream_timeout = 0 // timeout is disabled (default)
odrv0.axis0.stream_timeout = 500 // timeout 500ms
Thanks

**Comment by madcowswe** [comment]
Yes, good idea. I'll add it to the roadmap.

**Comment by Wetmelon** [comment]
Fixed in #316
