### ISSUE TITLE
Input processing module

### ISSUE THREAD

**Issue by madcowswe** [odriverobotics/ODrive#262]
For direct input from a user, over say PWM, we may wish to modify the setpoints. For example:
* Stick mixing
* Deadband (to stop micro rolling)
* Filtering/interpolation (See also #110)

**Comment by Wetmelon** [comment]
See also #280

**Comment by xsherlockpl** [comment]
I'd love to see that happen to do really precise RC equipment control of the motors

**Comment by Wetmelon** [comment]
We aren't adding any new large features to v3 firmware at this time, but we always accept a well-tested PR :)
