### ISSUE TITLE
Analog position feedback

### ISSUE THREAD

**Issue by madcowswe** [odriverobotics/ODrive#267]
Some servo systems use analog sin/cos feedback, or sometimes analog hall sensors. We have ADC capability on a fair number of pins on J3, so we should be able to accommodate this.

The signals have to fall in 0-3.3V, and if they don't some external circuitry to take it to that range will have to be added.

**Comment by metanoic** [comment]
The idea of replacing a hoverboard motor's digital sensors with analog has me pretty excited, I must say, as they are somewhat difficult to add encoders to.

**Comment by zbynekwinkler** [comment]
@metanoic Have you done any experiments with encoders in hoverboard motors?

**Comment by samuelsadok** [comment]
Analog sin/cos input support is now merged to `devel` (initial commit: a169dd33f0f452b84e30af161330b75d1f66f36d)
