### ISSUE TITLE
Collision of external interrupts

### ISSUE THREAD

**Issue by madcowswe** [odriverobotics/ODrive#268]
There will be problems if you assign a step signal to:
* GPIO3 and GPIO6
* GPIO4 and GPIO8
* M1 encoder index callback and GPIO7 don't like each other either

That last one is kinda bad, since GPIO7 is default step signal for M1

**Comment by madcowswe** [comment]
We have a process during the design of ODrive v4 to avoid collision of external interrupts.

**Comment by samuelsadok** [comment]
As for ODrive v3, there is now a variable called `odrv.misconfigured` which reads true if the device is configured such that there's an EXTI conflict. In this case one of the two conflicting interrupt functions will not receive trigger events but the device will otherwise function normally.
