### ISSUE TITLE
Revise brake current logic.

### ISSUE THREAD

**Issue by madcowswe** [odriverobotics/ODrive#269]
Now we dump ALL brake current in the resistor, and if it saturates we throw a fault. This is a bit inflexible.

New design:
* "Max regen current" config variable: the brake current above this level is sent to the brake resistor. This allows for controlled regen current into battries.
* Make a "regen current fault level" config variable: If the brake resistor is saturated, and the regen current that still flows into the supply exceeds this level, generate a fault. This fault would superseed the current brake saturation fault.

If both of the above variables are 0.0, then the behaviour is identical to the current behaviour, so there is no loss of generality.

**Comment by Wetmelon** [comment]
I don't see a real reason to use the "fault level" value.  If the regen is maxed out, AND we hit our brake saturation, then we can't do anything more and should throw a fault immediately
