### ISSUE TITLE
Arduino library: Missing SetCurrent()

### ISSUE THREAD

**Issue by LuSeKa** [odriverobotics/ODrive#282]
The Arduino library is currently missing a SetCurrent()-function, sth. like

 void SetCurrent(int motor_number, float current);

void ODriveArduino::SetCurrent(int motor_number, float current){
	serial_<< "c" << motor_number << " " << current << "\n";
}

Above code snippets are tested and working.

**Comment by madcowswe** [comment]
Great, thanks for the heads up.

**Comment by madcowswe** [comment]
This will be in the next release.
