### ISSUE TITLE
ChannelBrokenException() causing dead boards

### ISSUE THREAD

**Issue by ghost** [odriverobotics/ODrive#302]
## Problem 
I am trying to implement some very simple code to home my two motors. I have tested the code on two separate boards. The code usually works perfectly once or twice, and then fails with a "fibre.protocol.ChannelBrokenException" errors, after which the board's power LED turns off, and does not turn back on (dead board?), even after a Power Cycle. 

 I understand there is a branch dedicated to doing this, however, the point is not that I am failing to implement homing code, the point is that my boards are frying while implementing a very simple task. I am trying to work out what could be causing this problem. 

## Code 

```
def home_axis(odrive, gpio0, gpio1):

    axis0 = odrive.axis0
    axis1 = odrive.axis1

    # check calibrated
    check_calibration_status(axis0, 0)
    check_calibration_status(axis1, 1)

    set_closed_loop_control(axis0, 0)
    set_closed_loop_control(axis1, 1)

    while odrive.get_adc_voltage(gpio0) > 2.9 or odrive.get_adc_voltage(gpio1) > 2.9:
        if odrive.get_adc_voltage(gpio0) > 2.9:
            axis0.controller.pos_setpoint -= 100
        if odrive.get_adc_voltage(gpio1) > 2.9:
            axis1.controller.pos_setpoint -= 100

    offset0 = axis0.encoder.pos_estimate
    offset1 = axis1.encoder.pos_estimate

    return offset0, offset1

def set_closed_loop_control(axis, axis_id):
    print("Attempting to set state to closed loop control")
    axis.requested_state = AXIS_STATE_CLOSED_LOOP_CONTROL

    if axis.current_state == AXIS_STATE_CLOSED_LOOP_CONTROL:
        print("Axis {} in closed loop control". format(axis_id))
    else:
        print("HOMING FAILED!")
        print("Axis {} not in close loop control, perform recalibration".format(axis_id))


def check_calibration_status(axis, axis_id):
    print("Checking calibration condition of axis {}".format(axis_id))
    print("Motor{} calibrated: {}, Encoder calibrated: {}"
          .format(axis_id, axis.motor.is_calibrated, axis.encoder.is_ready))


if __name__ == '__main__':
    gpio0 = 4
    gpio1 = 3
    odrive = od.find_any()
    offset0, offset1 = home_axis(odrive, gpio0, gpio1)
    print(offset0, offset1)

``` 

## My hardware setup
- Power supply: 12V ~60A power supply.
- Motors: Turnigy Aerodrive SK3 - 6374-149KV Brushless Outrunner Motor
- Encoders: 8192 CPR ENCODER WITH CABLE (from odrive store) 

## Conclusion 

Please let me know if you think the problem is due to my hardware setup or my code?

**Comment by madcowswe** [comment]
Closing this, as we are providing support on Discord.
