### ISSUE TITLE
TUPs been updated, and broke the TravisCi. 

### ISSUE THREAD

**Issue by SJ-Innovation** [odriverobotics/ODrive#305]
Basically,

http://ppa.launchpad.net/jonathonf/tup/ubuntu/pool/main/t/tup/tup_0.7.5-0~16.04.york0_amd64.deb
No longer exists

and has been replaced with
http://ppa.launchpad.net/jonathonf/tup/ubuntu/pool/main/t/tup/tup_0.7.8-2~16.04.york0_amd64.deb

Would appreciate this being replaced in the Travis config so we can have Ci back...

Cheers!
Sam

**Comment by madcowswe** [comment]
Thanks for the heads up.

I updated the URL in .travis.yml. However there seems to be an issue:
```
No .tup directory found. Either create a Tupfile.ini file at the top of your project, or manually run 'tup init' there.
```

@samuelsadok can you please have a look?

**Comment by SJ-Innovation** [comment]
Updated TUP needs init before generation of database. 

Add:
`tup init`
to build.sh just above `tup generate`

Would love some form of write access to be able to perform this kind of maintenance myself, as opposed to bothering you with it. I'll become more active in the community before being cheeky and asking for that though!

**Comment by madcowswe** [comment]
@samuelsadok has fixed it on master and devel now.
