### ISSUE TITLE
Make on-board coupled axis control easier to implement

### ISSUE THREAD

**Issue by yconst** [odriverobotics/ODrive#306]
Implementing a controller that enables on-board coupled control of both axes is not straightforward in the current firmware because `Controller::update` is defined per axis. The Stanford Doggo team [implemented their per-axis controller](https://discourse.odriverobotics.com/t/stanford-doggo-project-an-odrive-powered-quadruped-robot/1674/12) that updates values on both axes each time, effectively running the same code twice in every iteration.

Could the firmware be modified in some way in order to facilitate coupled on-board control of both axes?

**Comment by Wetmelon** [comment]
Depends what you consider "coupled" control.  In our case, we handle the current control for each axis at 8kHz.  If a delay of no greater than 125 microseconds is sufficient, then we can simply "couple" the movement by *starting* it at the same time.

**Comment by madcowswe** [comment]
As ODrive v4 is single axis, and we expect to depricate v3 when v4 becomes stable enough, we need to couple axes over a communications link. Hence the approach would be general MIMO n-axis coupled control over a high speed communications link.

See #464.
