### ISSUE TITLE
Setting udev rules can fail for more reasons

### ISSUE THREAD

**Issue by chachi** [odriverobotics/ODrive#308]
Currently the setup.py udev rules configuration only allows for a `PermissionError` to pass (with a warning) and any other error (e.g. `CalledProcessError`) will fail. This means that if `udevadm control --reload-rules` fails for some reason, it is not possible to install `odrivetool`.

Relevant line:
https://github.com/madcowswe/ODrive/blob/451e79519637fdcf33f220f7dae9a28b15e014ba/tools/setup.py#L98

Workaround: make the udev rule immutable/unwriteable to force a `PermissionError` instead of another error, but this is pretty awkward.

**Comment by madcowswe** [comment]
Thanks for reporting this. I will change it to catch any exception and hence print a warning. Any rules related failure should still allow (degraded) installation.

**Comment by madcowswe** [comment]
Should be fixed on commit 035c899.
