### ISSUE TITLE
Plotting tools

### ISSUE THREAD

**Issue by madcowswe** [odriverobotics/ODrive#32]
Plotting of states, measurements and control effort in Python host.

- [x] Liveplotting of selected exposed variables over USB
- [x] Embedded variable oscilloscope: A oscilloscope-like buffer in firmware that can trigger on an event and hence log at the full sample rate of the control loop into a buffer: then transfer the buffer to the host.
This should use a circular buffer to allow pre/post trigger sampling: https://www.tek.com/sites/default/files/media/image/fig.7.png
(note: if the USB can send stuff in realtime fast enough, we might not need this)

Depends: #30

**Comment by madcowswe** [comment]
Liveplotting implementation suggestion:
The communication protocol allows "subscription" to a variable, with a specified trigger. One of the triggers is that the control loop has finished an execution. This is communicated to the communication thread from the control thread via a semaphore at the end of control loop.
The communication thread sends all data subscribed to on this trigger when the semaphore is triggered.

**Comment by Wetmelon** [comment]
You added the oscilloscope functionality, right?  Also, is this still relevant?
