### ISSUE TITLE
Feature Request: GUI for odrivetool

### ISSUE THREAD

**Issue by lsiempelkamp** [odriverobotics/ODrive#333]
Consider adding a user friendly GUI to replace/supplement the command-line-only odrivetool features.

**Comment by naktamello** [comment]
@lsiempel, there is a thread about UI on ODrive forum. If you haven't looked at it please check out the following link:
[https://discourse.odriverobotics.com/t/ui-for-odrivetool/1944/39](url)

**Comment by lsiempelkamp** [comment]
Thanks for getting back to me - but the url is dead?

**Comment by lsiempelkamp** [comment]
Nvm - url is live - hyperlink dead.

**Comment by lsiempelkamp** [comment]
Fantastic - will try to get this up and running!

Thanks for the heads up!

-Lewis
