### ISSUE TITLE
Issue error or warning that GPIOs overlap

### ISSUE THREAD

**Issue by Wetmelon** [odriverobotics/ODrive#339]
For instance, trying to use GPIO or 2 for an endstop with the default configuration clashes with the UART pins.  This should throw a configuration error or warning.

**Comment by samuelsadok** [comment]
This is addressed by the new `odrv.gpioX_mode` properties in #431: The user now needs to explicitly decide if a pin should be a UART pin or a general purpose input (or something else). For other types of clashes (e.g. EXTI numbers) there's now an `odrv.misconfigured` property.
