### ISSUE TITLE
Add better debugging support for non-developers

### ISSUE THREAD

**Issue by Wetmelon** [odriverobotics/ODrive#342]
Error codes are nice but it would be better if the user could easily dump variables or get some sort of printout of the ODrive state at the time an error occurred, for support & debugging purposes.

**Comment by Wetmelon** [comment]
Suggestions:

Some sort of error object that can store the state of important values at the time the error was thrown.

**Comment by samuelsadok** [comment]
I think the property subscription feature that targets full resolution (8kHz) property streaming will make a snapshot obsolete.
