### ISSUE TITLE
erase_configuration doesn't reset the "live" configuration to default

### ISSUE THREAD

**Issue by Wetmelon** [odriverobotics/ODrive#349]
When using "erase_configuration()", it erases everything in NVM but it doesn't reset ODrive to that state.  In other words, we don't trigger all of the "on value changed" callbacks that we have for the native protocol.  Optional

**Comment by samuelsadok** [comment]
This was fixed on RazorsFrozenTesting: 8cd673363c3943c3527f7018a1d5a1698b820094
