### ISSUE TITLE
Feed-forward control

### ISSUE THREAD

**Issue by madcowswe** [odriverobotics/ODrive#35]
- [x] We can now use the estimated model parameters to add feed-forward terms to the embedded controller.

- [x] Feasability filter
We need a feasability filter (rate limiter, etc) in front of the controller such that we can feed it feasible setpoints and hence have feasable feed-forward control effort.

**Comment by Wetmelon** [comment]
Added several filtered modes via #280:
* Vel Ramp Mode
* Torque Ramp Mode
* Trapezoidal Trajectory mode

bEMF and wL feedforward terms added for the current controller by @PAJohnson in f52c68b3a864245f8fa3dde0470a45b7796112dc

**Comment by Wetmelon** [comment]
Added 2nd order filter mode, other ramps etc.
