### ISSUE TITLE
find_idx_on_lockin_only should allow all locking states to find the index, not only the steady speed state.

### ISSUE THREAD

**Issue by je310** [odriverobotics/ODrive#361]
From what I can gather find_idx_on_lockin_only is used to not allow the index pin to be triggered on things like STATE_IDLE or during closed loop control. Though it also excludes LOCKIN_STATE_RAMP and LOCKIN_STATE_ACCELERATE which means that often the motor will need to spin past the index location. I think it should include all LOCKIN states, and exclude all non-lockin states.

**Comment by madcowswe** [comment]
The original intention with this setting was to be able to use the rising edge of a hall sensor as index. In this application it had to be completely certain the motor had a positive velocity (with margin) to make sure the rising edge = clockwise edge (or similarly for whatever polarity applies).

You could either have a very short acceleration ramp, or we can make a sparate setting like "allow_idx_find_always", and rename the current setting to "find_idx_on_lockin_full_speed_only" or similar.

**Comment by Wetmelon** [comment]
Added this feature some time ago...
