### ISSUE TITLE
can not import Logger from odrive.utils

### ISSUE THREAD

**Issue by ruixu2** [odriverobotics/ODrive#372]
`from odrive.utils import Logger, Event`
![image](https://user-images.githubusercontent.com/34615161/63659251-05c7e200-c7e3-11e9-9b37-1d843babca59.png)

**Comment by samuelsadok** [comment]
Is this in `run_tests.py`? If so, this script is now deprecated in favor of a bunch of new hardware-in-the-loop test scripts.
