### ISSUE TITLE
Refactor torque units

### ISSUE THREAD

**Issue by madcowswe** [odriverobotics/ODrive#380]
After the addition of the ACIM, it is not so clear cut that q axis current = torque. So we should abstract it so that `controller` can work with just torques.

Proposal:
1. `controller` works in torque units (you can put kT=1.0 Nm/A if you don't care about correct units)
2. `motor` provides a `effective_torque_limits()` function, so that `controller` can antiwindup correctly.
3.  `motor` is responsible to convert the torque setpoint from `controller` into currents. This will depend on motor type (PMSM, ACIM, Gimbal, etc), and also subject to inverter limits (modulation limit, power limits)

**Comment by PAJohnson** [comment]
Resolved with PR #426 - Change motor control input from A to Nm.
