### ISSUE TITLE
Allow feedback from anti-cogging

### ISSUE THREAD

**Issue by csik** [odriverobotics/ODrive#385]
I've been looking for a way to figure out when anti-cogging (which works great for me, btw) is finished, with no avail. I noticed in controller.hpp that you have the following todo:

    // TODO: anticogging overhaul:
    // - expose selected (all?) variables on protocol
    // - make calibration user experience similar to motor & encoder calibration
    // - use python tools to Fourier transform and write back the smoothed map or Fourier coefficients
    // - make the calibration persistent

Can you expose at least anticogging_.calib_anticogging so that we have a way to test if the process is finished?

**Comment by Wetmelon** [comment]
We're in the process of bringing through a lot of changes from RazorsEdge, which will include exposing those variables.  In the meantime, I would watch for the position to return to ~ 0 after it goes some distance.
