### ISSUE TITLE
error compiling for board arduino uno r3

### ISSUE THREAD

**Issue by kennethkneebone** [odriverobotics/ODrive#396]
doeas anyone have an idea of how to fix this and how to compile for an uno board?
also where is best to put the file Arduino.h as a library that arduino needs?
thankyou

**Comment by Wetmelon** [comment]
Hi Kenneth, you're going to have to be more specific.  The ODrive Arduino example should compile for Uno out of the box

**Comment by kennethkneebone** [comment]
i will have to look at maybe explaining by making a video or something, maybe later. thankyou
