### ISSUE TITLE
Adding USB serial, but need quick overview

### ISSUE THREAD

**Issue by nickaknudson** [odriverobotics/ODrive#4]
I intend to add USB serial support for ODrive but need a quick overview into how the motor control works. What control modes are currently available? Position control? Velocity control?

I don't see any functions to call into to control the motor. Is all control accomplished by modifying this exported structure?

https://github.com/madcowswe/ODriveFirmware/blob/master/MotorControl/low_level.h#L54

Thanks.

**Comment by madcowswe** [comment]
Position, velocity and torque control are implemented.
Gimme an little bit and I'll make some public functions you can call to set the desired values.

**Comment by nickaknudson** [comment]
Okay great. I'll get started on the USB interface. Thanks!

**Comment by madcowswe** [comment]
Okay done. Check these public functions: https://github.com/madcowswe/ODriveFirmware/blob/master/MotorControl/low_level.h#L75-L78

Call the the corresponding one depending on which mode of control you wish to do.
