### ISSUE TITLE
Feature request: Virtual temperature limit

### ISSUE THREAD

**Issue by dronus** [odriverobotics/ODrive#403]
Make the motor temperature available as controller limit. 

The temperature can be simulated by inegrating over the expected losses (estimated by current) and a user-defined thermal dissipation constant (K/W). High temperature then errors-out the drive (by an user-defined threshold) or limit drive current to keep the motor at a safe limit.

This is especially useful for unattended operation, where external conditions (eg. temporary blocking or temporary attached masses) may change drive characteristics unexpectedly and may result in overload.

**Comment by Wetmelon** [comment]
Implemented with physical sensors.  Set `motor.config.motor_thermistor`.

"Thermal Model" is a wontfix, but we will accept tested PRs
