### ISSUE TITLE
get_inverter_temp through ASCII no response

### ISSUE THREAD

**Issue by Peter-haotian-cui** [odriverobotics/ODrive#404]
Hi,

I use "r axis0.motor.get_inverter_temp" command for getting axis0 inverter temperature, but there is no response. Is it my command wrong? any suggestions? 
vbus_voltage and other commands are usable.

Thanks

**Comment by Wetmelon** [comment]
See forum post: https://discourse.odriverobotics.com/t/driving-two-motors-parallel/4550/3?u=wetmelon

**Comment by samuelsadok** [comment]
The `r` command of the ASCII protocol only supports reading properties whereas `axis0.motor.get_inverter_temp()` is (was) a function. With @Wetmelon's changes it's exposed as a property now (merged to the `devel` branch). That means you can read the temperature with `r axis0.motor.inverter_temp`.

@Wetmelon the forum post seems unrelated, probably mixed up a link there.

**Comment by Peter-haotian-cui** [comment]
Thanks!

**Comment by Wetmelon** [comment]
Workaround implemented, closing for now
