### ISSUE TITLE
Odrive V3.2  - Devel branch - No motor response for USB commands

### ISSUE THREAD

**Issue by Capo01** [odriverobotics/ODrive#41]
It looks like a recent change to the devel branch may have broken compatibility with V3.2 boards. Board is set to 3.2 in main.h and it complies and uploads without errors however commands sent over USB do not lead to any movement from the motor. This is true for both the echo command and using test_communications.py. Command is sent without errors, just no response. This is the same symptom as mentioned preciously on the forum [here](https://discourse.odriverobotics.com/t/firmware-v0-1-release/156/6). I uploaded the main brunch and no such issue so its definitely software related.

**Comment by madcowswe** [comment]
This issue is fixed in commit 7dc6a464 now pushed to devel.
