### ISSUE TITLE
Stuck in DRV8301_readSpi infinite loop when using absolute encoders

### ISSUE THREAD

**Issue by jhurliman** [odriverobotics/ODrive#420]
Here's my setup: ODrive 3.6-56V with AMT203-V absolute encoders with chip select pins connected to GPIO pins 7 and 8 for axis 0 and 1 respectively, running the latest firmware from `devel` (essentially the 0.5.0-rc). I was able to flash the new firmware, run the latest odrivetool, set the encoder CPR to 4096 and encoder mode to `SpiAbsCui` for axis0, then run motor calibration, encoder offset calibration, and go into closed loop control mode. Everything seemed great. However, when I powered the device off then powered it back on again, it refused to respond to requested_state commands. I flashed a debug version of the firmware and connected via ST-LINK, and found it was getting stuck on the following line in `drv8301.c`:

```
while((DRV8301_readSpi(handle,DRV8301_RegName_Status_1) & DRV8301_STATUS1_FAULT_BITS) != 0);
```

The value 0xFFFF was being returned each time, causing that check to fail.

If I set the encoder mode to 0 (Incremental) for both axes, save_configuration(), and reboot() I can get past that. Then, I can set the encoder mode back to 0x100 (SpiAbsCui) and set requested_state to AXIS_STATE_ENCODER_OFFSET_CALIBRATION. Then finally, closed loop control. But if I leave the encoder mode as SpiAbsCui and power cycle, I'm stuck back in that same startup loop.

**Comment by samuelsadok** [comment]
For  `encoder.config.mode` to take effect you _need_ to reboot actually. Then, after the reboot, you need to run offset calibration once and save it. See [here](https://github.com/madcowswe/ODrive/blob/rc-v0.5.0/docs/encoders.md).

Do you have the incremental output of the encoder also connected to the ODrive? If so, I think what's happening is that your encoder is just being used as a normal incremental encoder until reboot. For an SPI encoder you don't need to connect the A/B/Z lines at all.

The other thing is, looking at the datasheet, the protocols for [CUI AMT20x](https://www.cuidevices.com/product/resource/amt20.pdf) and [CUI AMT23x](https://www.cuidevices.com/product/resource/amt23.pdf) seem incompatible. The latter one is implemented in `rc-v0.5.0` while the former is not. Feel free to open a feature request issue for the AM20x (or better yet a PR).

**edit**: That doesn't really explain your hang yet. Could be an electrical issue. Maybe the encoder is pulling MISO up (that's shared with the DRV8301 chips). You could try disconnecting individual SPI lines or checking with an oscilloscope if there's anything on MISO.

**Comment by jhurliman** [comment]
We're going to order CUI AMT233B encoders and report back.

**Comment by jhurliman** [comment]
The `AMT203-V` encoders have been swapped out with a pair of `CUI AMT232B-V` encoders. I'm seeing the same issue with `DRV8301_readSpi()` continuously reading `0xFFFF` causing an infinite loop.

UPDATE: Unplugging both of the encoders causes the debugger to immediately jump to the next line (`osDelay(1);`) and successfully complete the startup sequence. Afterwards, it looks like I can plug the encoders back in. I'm testing if the encoders are usable after hotplugging.

UPDATE2: Yes, the encoder position updates as I turn the motor shaft after plugging one or both encoders back in after the startup sequence completes.

**Comment by jhurliman** [comment]
Oscilloscope for MISO with the encoder disconnected:

![encoder-disconnected](https://user-images.githubusercontent.com/195374/87232877-556db880-c377-11ea-9eee-fc2530f8121b.png)

With the encoder connected:

![encoder-connected](https://user-images.githubusercontent.com/195374/87232885-60284d80-c377-11ea-9b68-d48be28647aa.png)

We'll address this on the hardware side and report back. Thanks for the pointer.

**Comment by samuelsadok** [comment]
Maybe nCS is not connected properly to the encoder and as a result the encoder is permanently enabled. If you measure the encoder's nCS you should see a steady 8kHz signal after the ODrive has started successfully. If you don't see this you have perhaps connected nCS to the wrong pin.

**Comment by jhurliman** [comment]
Adding a pull-up resistor allowed us to successfully boot and go into idle state with the absolute encoders connected. However, there were various issues with calibration and even after hacking around them with unplugging and replugging we cannot get the device to go into closed loop control with absolute encoders connected and enabled. I tested #431 (merged into latest `devel`) to see if that improved the situation, but it seems to make things worse as we get stuck in the infinite loop both with and without the pull up resistor.

**Comment by samuelsadok** [comment]
Where did you add the pull-up resistor? DId you check if the 8kHz signal appears on the encoder's nCS?
Additionally, there's a hack you can try: add a resistor (something like 100Ω...1kΩ) on MISO between the encoder and ODrive (in series).

**Comment by wisitmax** [comment]
We added a 100k pull-up resistor between GPIO7 and 3.3V (did the same on GPIO8). After setting the encoder config and reboot, there's 8kHz signal on GPIO7 (we're testing with only one encoder/motor). Encoders appear to be working (pos_abs changes as the motor moves) as well.

![nCS on GPIO7 after reboot](https://user-images.githubusercontent.com/2425693/88581667-5d2d8e00-d002-11ea-98dd-75e30896cc8d.JPG)

**Comment by wisitmax** [comment]
Adding 1k res to the MISO line in series between encoder and ODrive fixes it.

**Comment by wisitmax** [comment]
However, when we use two encoders (each has 1k resistor in series on its MISO line), we got ERROR_ABS_SPI_COM_FAIL on both axes. 

Each encoder by itself works (i.e. leaving the other encoder unplugged). Both nCS pins have 8 kHz pulse.
![nCS on two encoders](https://user-images.githubusercontent.com/2425693/88609985-49058300-d03a-11ea-9f33-4c8dc67b2615.JPG)

**Comment by Wetmelon** [comment]
Ah, I wish I'd seen this before.  I tested the AMT203 encoders a couple of years ago and had this same problem.  They do technically function but I had all sorts of headaches.  IIRC I ended up putting a capacitor filter on CS but still regularly had problems getting the board to boot correctly.

I see the same problem as you, the lines are a bit sensitive to the clock output.

![image](https://user-images.githubusercontent.com/3612694/88618165-64868300-d066-11ea-8e96-105f808141f7.png)

**Comment by Wetmelon** [comment]
I actually connected the shield ring terminal (on the official cable) to ground, and it fixes everything :)
![image](https://user-images.githubusercontent.com/3612694/88619592-ea57fd80-d069-11ea-86bb-c4df69bf64d4.png)

**Comment by samuelsadok** [comment]
Lol so the SCLK signal induces ripples on nCS, causing spurious activations/deactivations of the AMT203's MISO output? From just looking at the nCS signal there I wouldn't have guessed that those ripples cause confusion at the encoder side. Is this measured close to the ODrive or close to the encoder?

**Comment by wisitmax** [comment]
I think I found the problem but I'm not sure how to fix it. As soon as I connect the 2nd MISO from the 2nd encoder, the MISO line (dark blue) got cut in about half.

yellow: nCS0
cyan: SCK
pink: nCS1
dark blue: MISO

With one encoder.
![dark blue MISO with 1 encoder](https://user-images.githubusercontent.com/2425693/88719523-448fa780-d0d8-11ea-8dab-f5fb37b25869.JPG)

With two encoders. MISO line (dark blue) got cut in half, LOW signal is ~2V.
![dark blue MISO with 2 encoders](https://user-images.githubusercontent.com/2425693/88719524-45283e00-d0d8-11ea-82c9-5a1c6f7eabc7.JPG)

**Comment by wisitmax** [comment]
It seems that the encoders are constantly talking on the MISO line. The presence of more than one would pull the MISO line high causing errors. We added a tri-state buffer gate (e.g. 74AHC1G125) on each encoder's MISO line and that fixed it.

**Comment by Wetmelon** [comment]
Yeah, something like this?  
![image](https://user-images.githubusercontent.com/3612694/88988318-8c642980-d2a6-11ea-81fe-07a23b2c7660.png)

**Comment by madcowswe** [comment]
I had a look at the datasheets, and indeed the CUI AMT203 uses SPI, the AMT232 actually claims to be SSI.
However, it's not quite standard SSI. Since they still have a "chip select" to frame the data, it seems more like SPI but without tristate. Strange choice, since it's not actually compatible with SSI.

Good thing ODrive v4 is single axis.

**Comment by Wetmelon** [comment]
We sent this information to CUI, and they confirmed there is a bug in the PCB and will be fixing it such that their SSI mode actually matches the datasheet. https://www.cuidevices.com/blog/integrating-absolute-encoders-an-overview-of-spi-rs-485-and-ssi-protocols#synchronous-serial-interface-ssi-

Additionally, `devel` branch will no longer block on DRV failure, but instead throw a DRV FAULT and proceed: 1d0fcc5fcffae2873ff8fbb499a5187c10dc11be

**Comment by wernerdaehn** [comment]
Just for confirmation, what is the summary of the problem? I'd like to replace the CUI encoder with an absolute encoder of same shape/dimensions. 
Am I correct in the assumption that with one encoder all is fine, the issue is when two encoders are connected?
And what will be the solution? CUI will change something or oDrive PCB?

**Comment by Wetmelon** [comment]
The MISO line doesn't tri-state properly.  You can just put a tri-state buffer on the line.  CUI is changing something, and we're coming out with an "Isolator" board that will effectively do the same thing

**Comment by joshmouch** [comment]
Is this fixed yet?

**Comment by Wetmelon** [comment]
> Is this fixed yet?

No, this is a hardware problem. The AMT203 needs a tri-state buffer on the MISO line or it will respond to SPI clock signals during DRV configuration at startup.

At least, I think so.  If the GPIOs are going low during startup then someone will need to submit a PR.  This code is not being developed further.  I recommend one of the new ODrive products which don't have this problem.

**Comment by Wetmelon** [comment]
> Is this fixed yet?

No, this is a hardware problem. The AMT203 needs a tri-state buffer on the MISO line or it will respond to SPI clock signals during DRV configuration at startup.

**Comment by joshmouch** [comment]
In your last post you said "CUI is changing something", so I thought that meant the hardware change.

**Comment by Wetmelon** [comment]
> In your last post you said "CUI is changing something", so I thought that meant the hardware change.

Oh, no idea.  CUI never got back to us and we've moved onto other problems.
