### ISSUE TITLE
Phase Resistance Measurement

### ISSUE THREAD

**Issue by zhongmu** [odriverobotics/ODrive#423]
The FOC loop runs with a integrator controller, then phA current becomes steady quickly. The phase resistance is caluculated as the voltage(controller output) divided by the command current.
However, the motor winding current is still discontinuous since MOSFESTS work in PWM mode. The inductance cannot be ignored.
Is it right to measure phase resistance in this way?

**Comment by samuelsadok** [comment]
For normal sized motors (*) the current renders a triangular waveform with a period of 48kHz (twice the PWM frequency). The current sampling happens almost exactly in the middle of the falling slope (up to a delay of 0.5µs). Thus we sample almost exactly the average current.

(*) if the phase inductance is very low and/or the phase resistance is very high (in other words a short time constant tau = L/R) then the triangle waveform starts becoming curved and the measured current won't be the correct average anymore. For reference the [D5065 motor](https://odriverobotics.com/shop/odrive-custom-motor-d5065) has roughly L = 16µH and R = 39mΩ. The curving starts to appear at L = 1µH and R = 39mΩ as can be seen in [this simulation](http://tinyurl.com/y842esnh). However then you also get huge current ripples so you'd probably want a higher switching frequency anyway.
