### ISSUE TITLE
Trapezoidal control looses force on engaging

### ISSUE THREAD

**Issue by dronus** [odriverobotics/ODrive#434]
If the control is running on high error (eg. closed loop control without integral, the motor won't reach target position) and trapezoidal movement is engaged via the move_to_pos command, the force drops and the motor gives way to external forces, before finally engaging again.

It just feels like the trajectory is planned by the current position and not the setpoint, although the code seems otherwise.

With setpoint control, by programming a target that can't be reached, the force can be controlled by choosing how far the setpoint is behind an obstacle.  However if using move_to_pos, the motor would be pushed back and then builds up force again  on any call of move_to_pos, even if  the programmed target would result in a higher final force.

Why is this, and how can it be prevented?

**Comment by Wetmelon** [comment]
move_to_pos is a very simplistic planner that uses the current position and velocity (assuming they're achievable) as the starting point of the control.  It is intended for _unrestricted_ point-to-point movement.  It is not intended for your use case, sorry :/

**Comment by dronus** [comment]
I thought it uses the current controller.pos_setpoint as the starting point? Code reads like this.
But the real movement feels like it starts at encoder.pos_estimate, even if pos_setpoint is already far off. That is what I am wondering about!

**Comment by Wetmelon** [comment]
> I thought it uses the current controller.pos_setpoint as the starting point?

Yes, and if you're operating the drive within its limits in Trapezoidal mode, then `pos_estimate` is approximately == `pos_setpoint`.  I'll look into it, it's possible the integrator is resetting for some reason?
