### ISSUE TITLE
M0 current loop noise/unstable

### ISSUE THREAD

**Issue by EMHacker-alt** [odriverobotics/ODrive#444]
I just brought 6 ODrive v3.6, and found out 2 of them M0 current loop are abnormal. And other boards, M0 current loop also has too much current noise compared to M1. The M0 motor either makes high frequency noise or vibration. I tested this only under current mode, so it is no possible that velocity or position loop affect this. And I tried to set the current i_gain to zero, only left the p_gain, but still the same. Further more, I reconnect the same motor and encoder to M1, no problem at all. This is weird, it seems like the current loop is unstable in high gain or some unknown lag caused this? 
Below is a waveform snapshot which shows the phase C PWM, current test point and the current waveform from an external isolated current probe.
![image](https://user-images.githubusercontent.com/67554208/88410761-5f78c800-ce09-11ea-8330-092691692a63.png)

**Comment by madcowswe** [comment]
Hi,
Are these ODrives official ones from odriverobotics.com/shop?
What kind of noise are you getting, do you have a video or other data showing it?
Assuming you are rotating the motor in the capture shown, this result looks normal to me.
What motor are you connected to?

**Comment by EMHacker-alt** [comment]
Hi, madcowswe,
These ODrives are all official ones from odriverobotics.com/shop. There is a youtube link https://youtu.be/r0csQ9wwq5I (Please volume up you can hear the noise) shows the motor and noise sound. The oscilloscope waveform shown was **under no current command and no motion at all.** The current captured is just under zero current setpoint. In other word, the noise current pk-pk is almost 1.7A ！At some angle, I can feel the motor is vibration. 

My motor is a 10 pole pair outrunner motor with 250uH line line inductance and 0.3ohm resistance. The encoder is AS5047P with ABI output.

**Comment by madcowswe** [comment]
Thanks for the video, this helps me recognize the sound.
I think indeed the current controller is a bit overtuned and getting a bit unstable. To be sure, can you check that your encoder is correctly reading 0 change in position in this test condition.
Assuming encoder is working fine: I suspect that the reason this is happening is because your motor inductance is quite high compared to most motors we have tested on. The current controller gains are derived from the specified bandwidth and the motor inductance. Can you try to set `motor.config.current_control_bandwidth = 500` or maybe even try 200 and see how that goes?

**Comment by EMHacker-alt** [comment]
Thanks for your advices! Changing the `current_control_bandwidth` to 200Hz greatly reduces the noise. While, I also can see that motion becomes slower than before. So I think higher current bandwidth is necessary. And I still curious about why Motor 1 has no problem at all even with 1000Hz current bandwidth? In addition, in order to eliminate the affect of encoder, I checked the AB pin of encoder, no pulses appears.

By the way, this problem also related to the specific hardwares, some of them are better and some of them are worse. Why?

**Comment by tombsar** [comment]
Same issue here. M0 emits a loud hissing noise in closed loop control. Official ODrive 3.6, official 5065 motor, default everything. M1 creates the same type of noise, but much quieter.

**Comment by Wetmelon** [comment]
Does this noise change depending on the firmware version loaded on the board?

**Comment by Wetmelon** [comment]
After reviewing the whole conversation, I'm going to close this with the workaround to use a higher current control bandwidth.
