### ISSUE TITLE
Encoder calibration current ramp-up

### ISSUE THREAD

**Issue by dronus** [odriverobotics/ODrive#445]
When odrive is used by a little bit heavier machines, the calibration can be complicated. Making the motor calibrate reliable requires calibration current close to the motor's limit. However, the open loop control established by calibration instantly ties the rotor to the origin phase angle. Depending on the initial rotor position, this gives a quite powerful jerk that make larger machines jump around and may kill belts / pulleys etc. 

I would suggest that there should be a short current ramping-up sequence for all open-loop controlled parts of the calibration process (motor winding and encoder offset calibration).

**Comment by samuelsadok** [comment]
This is implemented as part of #472: https://github.com/madcowswe/ODrive/blob/89f07226549312a7e311cae823d7cc0f15a8ae5f/Firmware/MotorControl/encoder.cpp#L225-L227

Half a second is allocated for the current to ramp up and an additional half of a second is allocated for the motor to snap to the zero-position.
