### ISSUE TITLE
Add G-Code support

### ISSUE THREAD

**Issue by madcowswe** [odriverobotics/ODrive#45]
We wish to have G-Code parsing and motion planning for stand-alone operation. Work has been started to port these parts of GRBL:
https://github.com/Hello1024/grbl

**Comment by madcowswe** [comment]
Many double literals are used in GRBL, we'd need to use `-fsingle-precision-constant`

**Comment by Hello1024** [comment]
#47 Addresses this.

**Comment by yhaiovyi** [comment]
May I ask why would you want a stand-alone operation with 2 motors only? Or am I missing something?
