### ISSUE TITLE
Dangerous state after canceling trapezoidal control 

### ISSUE THREAD

**Issue by dronus** [odriverobotics/ODrive#450]
If a trapezoidal motion is interrupted by setting axis state to AXIS_STATE_IDLE (eg. some kind of emergency stop) resuming operation is dangerous.
I've tried both

    axis.controller.move_to_pos(pos)
    axis.requested_state=AXIS_STATE_CLOSED_LOOP_CONTROL

and 

    axis.requested_state=AXIS_STATE_CLOSED_LOOP_CONTROL
    axis.controller.move_to_pos(pos)

but there is always a massive non-trapezoidal motion. Looks like the old motion was still dry-running in IDLE state and the new one is taking over a position that does not match reality. 

I've also tried adding `axis.controller.pos_setpoint=axis.encoder.pos_estimate` first, as there is some position error after interrupting the control of course, but there is still some non-trapezoidal motion.

Is there any safe procedure for recovering?

**Comment by dronus** [comment]
Seems the following sequence will mitgate the problem:

    axis.controller.pos_setpoint=axis.encoder.pos_estimate
    axis.controller.move_to_pos(axis.encoder.pos_estimate)
    axis.requested_state=AXIS_STATE_CLOSED_LOOP_CONTROL
    axis.controller.move_to_pos(pos)

It seems that the trajectory is always planned starting at `pos_setpoint`, not the real world state. Is this on purpose?

**Comment by Wetmelon** [comment]
What version is this on?  I believe this is fixed in the release candidate, as it initializes the input to the current position & updates the planner upon entering closed loop mode.

**Comment by dronus** [comment]
I think the code line in doubt is https://github.com/madcowswe/ODrive/blob/ffbeaed61b74cb23c522681b062a0337c601330d/Firmware/MotorControl/controller.cpp#L53
which is still in master. planTrapezoidal initializes on pos_setpoint_, which may be far away from encoder pos_estimate after idling.

**Comment by Wetmelon** [comment]
Yeah, this is taken care of in `devel`, it initializes pos_setpoint = pos_estimate upon entering closed loop.
