### ISSUE TITLE
Homing procedure still uses encoder count units - set_linear_count()

### ISSUE THREAD

**Issue by TobinHall** [odriverobotics/ODrive#455]
In the devel branch the axis homing procedure calls set_linear_count which sets the encoder position in encoder counts:
https://github.com/madcowswe/ODrive/blob/331448170cb68fa1bd675a6f8e4ee76122d709de/Firmware/MotorControl/axis.cpp#L429
`controller_.pos_setpoint_` has revolution units rather than encoder count. 

A possible fix is to replace the line with the following:
`encoder_.set_linear_count((int32_t)(controller_.pos_setpoint_ * (float)encoder_.config_.cpr));
`

But it may be better to replace `set_linear_count(int32_t count)` with something like `set_linear_pos(float pos)`.

`set_linear_count` is only used in the homing code above, in the encoder index callback, and in the odrive tool.

**Comment by samuelsadok** [comment]
Thanks for reporting this! It's [fixed](7fdaadf96e0ff39878930da41a0069712f3fcd8b) now as part of [v0.5.1-rc2](https://github.com/madcowswe/ODrive/releases/tag/v0.5.1-rc2).
