### ISSUE TITLE
Python 2 print does not support flush

### ISSUE THREAD

**Issue by tombsar** [odriverobotics/ODrive#458]
Usage of `print(..., flush=True)` is not compatible with Python 2. There are several instances of this in the dfu.py file. (https://github.com/madcowswe/ODrive/search?q=%22flush%3DTrue%22&unscoped_q=%22flush%3DTrue%22)

**Comment by samuelsadok** [comment]
This issue is a subset of #456 and fixed in 96cbe69f8aaabba669e39331e15ca364dd4e6eba.
