### ISSUE TITLE
Motor power sign check to prevent spinout

### ISSUE THREAD

**Issue by madcowswe** [odriverobotics/ODrive#462]
Incorrect encoder offset can lead to an uncontrolled spinout situation due to inadvertent flipped sign of torque production. Incorrect encoder offset can occur due to missed pulses in an incremental encoder, or general incorrect calibration.

Suggested algorithm:
Look for the case where torque_setpoint * omega is negative (we want to be braking), and then trip on pwr_estimate > margin.

Simple low pass filter of motor `V * I` dot product.
```
pwr = dot_product(v_d/q, i_measured_d/q)
pwr_estimate += k * (pwr - pwr_estimate);
```

**Comment by Wetmelon** [comment]
Implemented on 0.5.2 or 0.5.3...
