### ISSUE TITLE
Review setpoint transients

### ISSUE THREAD

**Issue by madcowswe** [odriverobotics/ODrive#465]
Some people have reported transients (snap to a location) when changing modes. (not sure if it was input mode or control mode).

We should do a review of the main state transitions and see if we need to add de-transient (set setpoint to estimated pos/vel/...).

It probably makes sense to reset setpoints when transitioning “up” the control chain, e.g. from current to vel it should reset vel, from vel to pos: reset pos.

perhaps we can have de-transient be an option
probably on by default, and some documentation about it. If people really do want to snap to the old setpoint, or more likely: have manually loaded the new setpoint before the transition, they can disable the de-transient option.

**Comment by Wetmelon** [comment]
This has largely been fixed over time as bug reports come in.
