### ISSUE TITLE
Detect encoder calibration problems (like obstructions)

### ISSUE THREAD

**Issue by madcowswe** [odriverobotics/ODrive#48]
We can start the encoder calibration with a short initial move to resolve the direction. Then once we start the fwd/rev scan we can simply have a window of allowed encoder values as we scan. If the window is violated, the calibration fails.

**Comment by Wetmelon** [comment]
The Encoder CPR code that was just implemented should correctly error out on obstruction too.

**Comment by madcowswe** [comment]
True! That means:
Done by #114 .
