### ISSUE TITLE
Odrive tool full catalog / index including configs

### ISSUE THREAD

**Issue by valentin-martinez-gama** [odriverobotics/ODrive#480]
Right now the most exhaustive single list of Odrive tool capabilities is the [Parameters and Commands](https://docs.odriverobotics.com/commands) section of the documentation. Does this document contain the **all** available commands? However, a list of all possible **configs**  doesn't seem to available in the documentation? 

Is it implicitly stated in one source code file? If yes, which file?

It would be nice to have **all of the Odrive tool commands, functions, and configs** in one large list somewhere in the documentation. This would allow users to be able to visualize the full range of the Odrive capabilities and get an idea of how to interact without having to browse through the different documents.

This index could include links to the other existing readmes that contain more detailed information on how to use the function or the implications of changing a given parameter.

I can gladly contribute to this issue. Just wanted to check out first what you guys think and if you can help me locate the info to start working on documenting it.

**Comment by samuelsadok** [comment]
The Parameters/Commands page only provides a very rough overview.

The kind of documentation you're asking for is something that we worked on recently and it will go live very soon, see here for more info: https://github.com/madcowswe/ODrive/issues/381#issuecomment-683758135.

The yaml file linked there is complete in terms of what functions and properties are listed there but many of them don't have a documentation text yet. You're very welcome to help expand this file. If you do, it's best to work from the `v0.5.1-rc2` branch so we can merge it to `master` later on. Note that there are also a lot of obscure properties that are only for power users and not tested to the full extent. If you want to get really fancy you can also [generate the documentation webpage yourself](https://github.com/madcowswe/ODrive/blob/devel/docs/developer-guide.md#documentation).
