### ISSUE TITLE
Odrive not obeying vel_setpoint set to stop?

### ISSUE THREAD

**Issue by Patronics** [odriverobotics/ODrive#493]
As far as I can tell, the odrive isn't obeying the axis1.controller.vel_setpoint, and it moves continuously at the same speed (but will change direction on command). I've followed all the steps for the hoverboard motor instructions (as that's what I'm using), and it works fine to start the motor, but setting vel_setpoint to 0 seems to have no effect, the motor keeps spinning. axis1.controller.config.control_mode is set to CTRL_MODE_VELOCITY_CONTROL, and the state is set to AXIS_STATE_CLOSED_LOOP_CONTROL. Yet the motor keeps running continuously? what am I missing?

**Comment by Wetmelon** [comment]
Hi Patronics, do you have anything set for current_setpoint?

**Comment by Patronics** [comment]
I believe it was set to zero as well, but I'd have to double check. How should that effect things? I thought that would only be used if control_mode was set CTRL_MODE_CURRENT_CONTROL? Thanks for any help!

**Comment by Patronics** [comment]
I just ran `odrivetool dfu` and updated the firmware (apparently from 4.11-dev to 4.12), and it seems like that may have fixed the issue. I still need to test a bit more with the control method I've been using, but this issue might have been resolved by the firmware update :)

**Comment by Wetmelon** [comment]
Oh my yes, 4.11 is quite old.  We just released 5.1, which should get picked up by `odrivetool dfu` soon..
