### ISSUE TITLE
Homing based on encoder index only

### ISSUE THREAD

**Issue by valentin-martinez-gama** [odriverobotics/ODrive#498]
The new [Endstops and Homing](https://docs.odriverobotics.com/endstops) feature is based on outside sensors and GIOP connections. 

As shared in the [Parallel Robot project community thread](https://discourse.odriverobotics.com/t/odrive-advanced-control-for-parallel-robot-project/5498) we had a similar "homing" issue but nothing more than the `AXIS_STATE_ENCODER_INDEX_SEARCH` and `set_linear_count()` functions were needed to `home` our robot motors. 

We used the following python script executed directly from the odrivetool. (Note: I removed the repeated code lines for axis1 for simplicity)

```python
def set_encoder_zero(odrv, axis0_offset=460, axis1_offset=690):

    odrv.axis0.requested_state = AXIS_STATE_ENCODER_INDEX_SEARCH
    wait_for_idle(odrv.axis0)

    odrv.axis0.requested_state = AXIS_STATE_CLOSED_LOOP_CONTROL
    odrv.axis0.controller.config.control_mode = CTRL_MODE_POSITION_CONTROL

    odrv.axis0.controller.pos_setpoint = axis0_offset
    time.sleep(.5)

    odrv.axis0.encoder.set_linear_count(0)
    time.sleep(.5)

    odrv.axis0.controller.pos_setpoint = 0
    return "DONE set encoder zero - home robot"
```

I think a homing procedure based on index search alone would be good enough for many if not most of the odrive applications. Especially when considering the encoder index can be aligned to be close enough to the machine 0 position during installation. 

I think it would be a good idea to at least include something like this in the documentation and even maybe integrate this idea to be easily used with the homing code and instructions already in place.

**Comment by Wetmelon** [comment]
Please submit a PR if this is still a desirable feature.
