### ISSUE TITLE
Enable current control checks during motor calibration

### ISSUE THREAD

**Issue by samuelsadok** [odriverobotics/ODrive#522]
Currently we don't run current limit checks during motor calibration. If the motor phases are accidentally shorted this could lead to oscillation and fry the ODrive.

With the integral gain `kI = 10.0f` that's currently used, the current overshoots if (and only if) the motor snaps to align with I_alpha.

![motor calib](https://user-images.githubusercontent.com/11528690/98697966-ccdb4500-2375-11eb-98c5-0bef3e257bdf.png)

**Comment by madcowswe** [comment]
We should probably reduce the `kI` a bit.

**Comment by samuelsadok** [comment]
Ok I changed kI to 1.0 in 18a391c092a2dfcd190fe25077f8b3c119427ed2.

For comparison, here's the log with kI = 2.0 and kI = 1.0:

![image](https://user-images.githubusercontent.com/11528690/99287048-0c080b00-283a-11eb-9e21-dcce310c835d.png)
Maximum observed I_alpha: 13.5 A

![image](https://user-images.githubusercontent.com/11528690/99287651-d31c6600-283a-11eb-9a7a-d93a51004d5c.png)
Maximum observed I_alpha: 11.3 A

The total duration of the motor resistance calibration is 3s (24'000 samples) so there is still easily enough time for the controller to settle.

**Comment by samuelsadok** [comment]
This is merged to `devel` now.
