### ISSUE TITLE
Anticogging improvments

### ISSUE THREAD

**Issue by madcowswe** [odriverobotics/ODrive#53]
- [x] Use setpoint instead of current position to lookup table, in order to keep the compensation on the feed-forward path only
- [ ] Selected harmonics smoothing
  - Upload calibration map
  - FFT - select harmonics - IFFT in python
  - Download smooothed map

**Comment by Wetmelon** [comment]
Thinking about this... would it be best to use a position prediction based on p & v, then take something like  (prediction + current pos) / 2 as the lookup value?

**Comment by madcowswe** [comment]
A more concrete plan for the 2nd part:
1. modify the firmware to scan into a small circular buffer with a "last written idx"
2. get python to poll it and read the buffer to capture the data
3. run and plot my analysis script as usual, make sure that still works
4. said script generates the smoothed version of the cogmap: resample this into a smaller cogbuffer, size TBD, something like 128 samples maybe 256.
5. Write this resampled cogmap back to ODrive.
6. modify the anticogging path that's called in every control cycle to use this smaller map and to simply linearly interpolate the nearest samples
7. figure out a way to store the cogmap as a config member as to make it stay in persistent memory

**Comment by Wetmelon** [comment]
If used in conjuction with trajPlan, anticogging is now placed in the feedforward path.

**Comment by madcowswe** [comment]
We plan to use a continuously rolling "integrator" with LPF broadcast of integrand. This supersedes the plans in this issue.
