### ISSUE TITLE
Disable returning to 0 velocity point after inertia moving

### ISSUE THREAD

**Issue by KuDeSnik33ra** [odriverobotics/ODrive#543]
I am implementing joystick control of robot - and then I release joystick - robot should just stop asap, but not move back to point there it was at the moment then I sent cmd "vel_setpoint 0". I use CONTROL_MODE_VELOCITY_CONTROL and 0.4.12 firmware. How can I achive such behaviour?

**Comment by Wetmelon** [comment]
Answered on forum https://discourse.odriverobotics.com/t/disable-inertia-compensation/6171/2
