### ISSUE TITLE
Separate printf from other communication.

### ISSUE THREAD

**Issue by madcowswe** [odriverobotics/ODrive#55]
Printf is usueful for debugging and casual status printing. However, now the transport used for printf is shared with the primary communication protocols.

We should use an escape bit in the USB communication protocol to route the debug printf's to the screen. No action is required to do this over UART, since the lack of sync char can separate it.

**Comment by samuelsadok** [comment]
By now on current devel you can use `CONFIG_USB_PROTOCOL=stdout` or `CONFIG_UART_PROTOCOL=stdout`. Given that we mostly debug using cortex-debug and the native protocol I believe that we have most use cases covered.

**Comment by madcowswe** [comment]
Closed with release of fw-v0.4.0
