### ISSUE TITLE
v0.5.2 release

### ISSUE THREAD

**Issue by PAJohnson** [odriverobotics/ODrive#562]
The ODrive firmware is due for a release. Many changes have been implemented since the last release.

Branch `fw-v0.5.2rc1` will be used for working in the proposed changes.

The most substantial collection of changes is related to the [Control Loop Refactoring](https://github.com/odriverobotics/ODrive/pull/472). Among other things, the CLR frees up CPU time. CPU time is suspected to be cause of mysterious DEADLINE_MISSED errors in relation to RC_PWM usage and INPUT_MODE_TRAP_TRAJ.

The suggested cutoff for the next release is commit `d5ba094` on Jan 19, 2021. This commit has the firmware at a state where libfibre is implemented, the CLR has been merged in, and the GUI is updated to operate with libfibre.

In addition, the following commits have been suggested for cherry picking into this release:

- [x] `a406aa0` - [Fix benign DFU errors](https://github.com/odriverobotics/ODrive/commit/a406aa062071c34a7cc881c76a0829582486a88c)
- [x] `b178357` - [Fix DFU](https://github.com/odriverobotics/ODrive/commit/b178357680329061ba147af4b61a1dee47b16339)
- [x] `2287f50` - [Add thermistor 2nd order lowpass filter](https://github.com/odriverobotics/ODrive/commit/2287f500034545d7bff9d4eb1ea3675ce9265916) - the original commit relied on some refactoring that should not be pulled in. Equivalent functionality added by commit `5fd1eab`
- [x] `801d9a1` - [run encoder.apply_config on successful dir_find](https://github.com/odriverobotics/ODrive/commit/801d9a190b5f90820141604c5dcde1fc5669ab18)
- [x] `4d5a75d` - [remove stray file](https://github.com/odriverobotics/ODrive/commit/4d5a75dd6e148eb1c0e7642a4dd69f2bae103f4f)
- [x] `378b743` - [fix macOS CI](https://github.com/odriverobotics/ODrive/commit/378b743392cf0a355afe94d07a07c703ab764af1)
- [x] `bddae0e` - [implement 2-norm current clamping](https://github.com/odriverobotics/ODrive/commit/bddae0e0d7c820818db9734b488db10729ef220f)
- [x] `63bd279` - [let acim identification run model without data](https://github.com/odriverobotics/ODrive/commit/63bd2799ebae4250a716bfc4d005f9dcca61482b)
- [x] `31f671d` - Fix odrivetool by adding the dll path on windows
- [x] `959d79b` - [fibre] fix handling of multiple devices
- [x] `de6105e` - [fibre-cpp] fix function calls with multiple args
- [x] `014eda2` - better errors when using lost objects
- [x] `351823a` - [libfibre] make pseudo-parallel func calls work
- [x] `0bf380b` - add AArch64 libfibre binary 
- [x] Add spinout detection from PR #477 
- [x] Verify performance when controlling two motors in RC PWM mode (+ trap traj)
- [x] Verify performance when controlling two motors with step/dir
- [x] Homing fixes
- [x] Input pos filter performance in circular position mode 
- [x] Changelog update
- [x] Docs update

**Comment by Wetmelon** [comment]
Released!
