### ISSUE TITLE
firmware 5.2 softbricks single ODESC3.6

### ISSUE THREAD

**Issue by Kezii** [odriverobotics/ODrive#578]
Firmware 5.2 from github releases renders ODESC3.6 unusable, to the point it doesn't show up as an usb device, while 5.1 works

```
> sudo st-flash --reset write ODriveFirmware_v3.6-24V_5.1.bin 0x08000000
[...]
> lsusb | grep -i odrive
Bus 005 Device 035: ID 1209:0d32 Generic ODrive Robotics ODrive v3
```

```
> sudo st-flash --reset write ODriveFirmware_v3.6-24V_5.2.bin 0x08000000 
[...]
> lsusb | grep -i odrive
```

this is reproducible every time

**Comment by madcowswe** [comment]
Hi,
We do not support unofficial hardware. Please contact the vendor of your board to see if they can fix the underlying issue for you.

**Comment by marja0900** [comment]
Is this true? Odrive bricks odesc? I thought it was open-source

**Comment by madcowswe** [comment]
In this scenario, if the vendor provides a board that is incompatible with the official firmware, and a user installs that firmware on the board, resulting in failure, then the vendor bears responsibility for mislabeling. Claiming compatibility in such cases is misleading and should be corrected.

**Comment by marja0900** [comment]
Can you give me a straight answer. I don't mind paying I just need to know if it's open source of if I'm wasting my time.

**Comment by samuelsadok** [comment]
Firmware for ODrive 3.6 is open source (this repository). Firmware for newer ODrive models (Pro/S1/Micro) is not.
