### ISSUE TITLE
enable_sensorless_mode does not appear in odrv0.axis0.config

### ISSUE THREAD

**Issue by drewpilcher** [odriverobotics/ODrive#579]
**Describe the bug**
When using odrivetool and attempting to set enable_sensorless_mode to true, the operation fails, and the parameter is not listed when executing the command odrv0.axis0.config

**To Reproduce**
Connect odrive V3.6, fw version 5.1 via USB to odrive tool. Execute the following command from the [sensorless setup tutorial](https://docs.odriverobotics.com/commands.html#setting-up-sensorless), note that it fails:

`odrv0.axis0.config.enable_sensorless_mode = True`

**Desktop:**
 - OS: Windows 10
 - odrivetool Version v0.5.2.post0

**Additional context**
I noticed that enable_sensorless_mode *is* listed in odrive-interface.yaml, but for some reason it's not appearing in the list.

**Comment by samuelsadok** [comment]
This variable was introduced in firmware version 0.5.2.
Please [update your firmware](https://docs.odriverobotics.com/odrivetool#device-firmware-update) or refer to the [old documentation](https://github.com/odriverobotics/ODrive/blob/fw-v0.5.1/docs/commands.md#setting-up-sensorless).
