### ISSUE TITLE
v0.5.2 Version Strings Are Wrong

### ISSUE THREAD

**Issue by CthulhuLabs** [odriverobotics/ODrive#589]
Something is wrong with the versioning info in the v0.5.2 release. I have updated with "odrivetool dfu" as well as with openocd with a st-link. Attached is the output from doing so. 
[Odrive Upgrade Output.txt](https://github.com/odriverobotics/ODrive/files/6720245/Odrive.Upgrade.Output.txt)
It looks like the v0.5.2 release has the version string set to v0.5.1-dev.

**Comment by samuelsadok** [comment]
Yes the firmware binary contains the wrong version number, this will be fixed in 0.5.3.

**Comment by CthulhuLabs** [comment]
You should mention that in the discourse release thread:

https://discourse.odriverobotics.com/t/firmware-0-5-2-release-thread/7151

I have seen a number of people confused by this on Discord.

**Comment by Wetmelon** [comment]
Done.  Thanks
