### ISSUE TITLE
Add custom control commands

### ISSUE THREAD

**Issue by Second222None** [odriverobotics/ODrive#595]
I am always frustrated when I try to add my own control commands from odrivetool.
Especially, in the following function
```c
void usb_rx_process_packet(uint8_t *buf, uint32_t len, uint8_t endpoint_pair) {
   if (endpoint_pair == CDC_OUT_EP && usb_cdc_rx_stream.rx_end_) {
       usb_cdc_rx_stream.rx_end_ += len;
       osMessagePut(usb_event_queue, 5, 0);
   } else if (endpoint_pair == ODRIVE_OUT_EP && usb_native_rx_stream.rx_end_) {
       usb_native_rx_stream.rx_end_ += len;
       osMessagePut(usb_event_queue, 6, 0);
   }
}
```
Where the incoming data in `buf` is processed?
Or
Which function is responsible for decoding the commands from PC?

**Comment by Wetmelon** [comment]
Oh that's in the native protocol.  If you look in the [odrive-interface.yaml](https://github.com/odriverobotics/ODrive/blob/master/Firmware/odrive-interface.yaml), you can add an object or function to the appropriate place there.  Then during compilation, the processing function are generated/defined in files in the Firmware/autogen folder.  It will automatically generate the interface and as long as the function that you define is in the right spot, it will work.

I'm going to close this for now, please post on the [forum](https://discourse.odriverobotics.com/) or join us on Discord if you'd like help with this
