### ISSUE TITLE
ODrive GUI -> fibre.Domain unknow

### ISSUE THREAD

**Issue by kimpixel** [odriverobotics/ODrive#597]
fibre has no attribute/function "Domain"

-Windows 10
-latest python

commit "ODrive-fb669109a26a5ba74d38897f1326a8d51b4f410e" was working but latest not.

**Comment by samuelsadok** [comment]
We're currently reworking the GUI so we're not maintaining the current Beta GUI anymore. However feel free to debug the issue and make a PR if you find a fix.
