### ISSUE TITLE
"Oh no odrv0 disappeared" message on Ubuntu 20.04 after odrv0.save_configuration()

### ISSUE THREAD

**Issue by mirano-Pat** [odriverobotics/ODrive#602]
After "odrv0.save_configuration()", I get the message "Oh no odrv0 disappeared" message and after few seconds I get a message "Reconnected to ODrive 2xxxxxxxxxx8 as odrv0."

ODrive board: 24V ODRIVE V3.6  
Frimware: v0.5.2  
OS: Ubuntu 20.04 LTS

```bash
$ odrivetool
ODrive control utility v0.5.2.post0
Connected to ODrive 2xxxxxxxxxx8 as odrv0
Website: https://odriverobotics.com/
Docs: https://docs.odriverobotics.com/
Forums: https://discourse.odriverobotics.com/
Discord: https://discord.gg/k3ZZ3mS
Github: https://github.com/madcowswe/ODrive/

Please connect your ODrive. 
You can also type help() or quit(). 

In [1]: odrv0.save_configuration()
Oh no odrv0 disappeared 

Reconnected to ODrive 2xxxxxxxxxx8 as odrv0
```

**Comment by samuelsadok** [comment]
This is normal behavior. Saving configuration is followed by an automatic reboot because it can halt the CPU for a short while, potentially resulting in missed encoder steps.

**Comment by mirano-Pat** [comment]
@samuelsadok 
Thanks. Thank you for your help !
