### ISSUE TITLE
Extend HWIL tests to include disconnected braking resistor situation

### ISSUE THREAD

**Issue by Wetmelon** [odriverobotics/ODrive#611]
Suggestion to force this in firmware by modifying brake timings rather than a control element in series with the braking resistor.

**Comment by madcowswe** [comment]
If this is quick and easy to add to the v3 tests we can do this. I can't imagine it will do anything other than trip the overvoltage, but doesn't hurt to check.

**Comment by samuelsadok** [comment]
I don't think it's quick/easy enough for us to work on it in this context.
