### ISSUE TITLE
Homing fails with MIN ENDSTOP PRESSED

### ISSUE THREAD

**Issue by Wetmelon** [odriverobotics/ODrive#625]
**Describe the bug**
I have setup an odrive with firmware v0.5.3 and configured following the docs instructions.
I enabled min endstop for the axis and set it to search home on it
After calibration, on startup, the motor starts searching for the min endstop as configured but, when the switch is pressed, the motor spins uncontrollably and looses closed loop control, displaying AXIS_ERROR_MIN_ENDSTOP_PRESSED.
The switch is NC.
Since I am pressing the switch by hand while the motor is rotating on a test bench could I be interfering with the odrives homing procedure?
How can I solve this problem?
Also tested on v0.5.2 but the same problem occurs.

**Additional context**
https://discourse.odriverobotics.com/t/axis-error-min-endstop-pressed-after-homing-on-startup/7814/2

**Comment by powerbling** [comment]
Are there any developments on this issue?

**Comment by Wetmelon** [comment]
Fixed in #710
