### ISSUE TITLE
Please add the ability to change vel_gain and pos_gain via CAN protocol

### ISSUE THREAD

**Issue by ale-novo** [odriverobotics/ODrive#628]
At the moment its not possible to change the following parameters using CAN
axis0.controller.config.vel_gain
axis0.controller.config.pos_gain
Please create new CAN messages to enable changing these parameters with the CAN protocol.

Usb connection is unreliable with EMI interference and i need to migrate my system into the more stable CAN protocol.
I change the gains on real time in my application and with usb the connection drops frequently.
Thanks a lot

**Comment by ale-novo** [comment]
a pr was raised for this:
https://github.com/odriverobotics/ODrive/pull/630

**Comment by Wetmelon** [comment]
Merged in #630.
