### ISSUE TITLE
the ODrive  board hardware  can opensource？

### ISSUE THREAD

**Issue by zouzhe1** [odriverobotics/ODrive#633]
i cant find  same about the ODrvie hardware  files
i want to DIY a board
i can find sale on alibaba ,but it is too high price.

**Comment by samuelsadok** [comment]
You can find hardware files up to version v3.5 here: https://github.com/madcowswe/ODriveHardware

**Comment by chrisgraf** [comment]
So is the ODrive not open hardware anymore?
