### ISSUE TITLE
Homing doesn't apply min_endstop offset.

### ISSUE THREAD

**Issue by Jostikas** [odriverobotics/ODrive#634]
ODriveTool v 0.5.4
FW installed 0.5.4, but firmware has 0.5.3-1

When homing, the min endswitch offset is no longer applied: after homing, the endswitch actuation point is the estimated_pos=0 point. While I appreciate that cf. 0.5.1 entering closed loop control no longer moves the axis, it seems the homing offset logic has gone out with the bathwater?

**Comment by Wetmelon** [comment]
Similar to #625 , we discovered some thread synchronization issues with homing, and it should be fixed in the next update.  Thanks for catching this.
