### ISSUE TITLE
Support encoder index pulse

### ISSUE THREAD

**Issue by madcowswe** [odriverobotics/ODrive#64]
- [x] Set up the ENC_Z lines as interrupt-in mode, and then in the interrupt go set the encoder's TIM->Instance->CNT value to 0; followed by disabling the interrupt, and setting a "we are zeroed" variable to true
- [x] Startup feature to "limp the motor over to the index pulse"

**Comment by Wetmelon** [comment]
ENC_Z interrupts are working on my end, just need to figure out how to fix my branch issue (right now, it will try to include USB Descriptor reporting PR too because I put it on devel like a dingus)

**Comment by fluture** [comment]
Can the index pulse be configurable?
I am using [AS5304](https://www.mouser.com/ProductDetail/985-AS5304AB) with these [magnetic rings](http://ams.com/eng/Products/Magnetic-Position-Sensors/Magnets/AS5000-MR20-44)
These have 44 index pulses per revolution (it depends on the number of poles)
While  [AS5047](https://www.mouser.com/productdetail/ams/as5047p-ts_ek_ab) has only one index pulse per revolution while using the ABI interface

**Comment by madcowswe** [comment]
@fluture You cannot have fewer index pulses than the number of pole pairs, because the encoder ring aliases. I.e. there is no way for the encoder to know which cycle you are in.

**Comment by fluture** [comment]
I don't want fewer, I was just thinking how or if it would work with magnetic rings which have more than one index pulse per revolution, I understand that the most common way is to have one per revolution (360 mechanical degrees) like the AS5047

**Comment by madcowswe** [comment]
I see. If you get the same number of pole pairs in the ring as there are in the motor, you can use the index pulse to restore the encoder calibration, just like a 1-index-pulse encoder.
However, you cannot restore the anti-cogging calibration.

**Comment by Wetmelon** [comment]
Closed by #106
