### ISSUE TITLE
PWM input

### ISSUE THREAD

**Issue by madcowswe** [odriverobotics/ODrive#65]

**Comment by Wetmelon** [comment]
Per discord:

* Configurable input with programmable modes, such as "ESC" mode (velocity) or "hobby servo", or any others we can think of.

**Comment by urdman** [comment]
Please can there be a PWM toque input? Thanks

**Comment by madcowswe** [comment]
Yes, the PWM input will be able to configure to map to any variable you would like, including current_setpoint (torque), or anything else.

**Comment by madcowswe** [comment]
There is now a preview for the hoverboard motor config writeup [here](https://github.com/madcowswe/ODrive/blob/devel/docs/hoverboard.md), including how to set up PWM input mapping.

**Comment by madcowswe** [comment]
Implemented in fw-v0.4.2
