### ISSUE TITLE
#please connect your Odrive 

### ISSUE THREAD

**Issue by HusamZain** [odriverobotics/ODrive#657]
Hi !
I’m new to this. I'm using odrive v3.6-56V
I was working on the odrive using ubuntu 20.04 connected via USB, and used odrivetools to perform some commands that were listed on the getting started page. and also connected the odrive using ros2 and everything was perfect, now suddenly when I try to connect the odrive using odrivetool or ros2 I got ''please connect your odrive and it seems the USB is no longer detectable.
I tried out different cables and used different pc and jetson nano kit, still the same things.
I change it to dfu mode (moved the switch from run to dfu) and still not detectable.
Does anyone know how to solve this issue?

**Comment by samuelsadok** [comment]
> it seems the USB is no longer detectable

Does that mean it doesn't show up in `lsusb` anymore? When you put it into DFU mode the name in `lsusb` should be something like "STM32 Bootloader".

If it still shows in `lsusb` in DFU mode, you might be able to recover it using `odrivetool dfu`.

If it doesn't show in `lsusb` at all, it's possible that the MCU got fried somehow. If you think this could be a manufacturing issue please email info@odriverobotics.com with a link to this thread and the following info:
 - Your order number
 - A brief description/list/picture of what you have wired up to the ODrive (power supply, motor, encoder, other external MCUs, ...)
 - A description of what the ODrive was doing at the time when the issue appeared

**Comment by Wetmelon** [comment]
Please post to the forum or ask on the discord channel if this is still an issue.
