### ISSUE TITLE
Please add PWM mode: PWM+- or  PWM+ DIR or PWM one wire 0-50-100

### ISSUE THREAD

**Issue by active-game** [odriverobotics/ODrive#668]
I'm trying to make a steering wheel using MMOS or EMC type controllers, they all output a PWM signal: PWM+- or PWM+ DIR or PWM one wire 0-50-100 , but none of these PWM signals support odrive !
Please add this feature, I will be very grateful!

**Comment by Wetmelon** [comment]
Can you be more specific please?  What is PWM +-?

**Comment by active-game** [comment]
> Can you be more specific please? What is PWM +-?

I mean Left and Right channels 2 wire PWM like on BTS7960

**Comment by madcowswe** [comment]
My interpretation is the following:

> PWM+-

two wires: pwm 0-100% to go forward, pwm the other signal to go backwards

> PWM+ DIR

0-100% PWM and a digital direction signal

> 0-50-100

0% pwm max speed one way, 50% PWM stop, 100% pwm max speed the other way.

**Comment by active-game** [comment]
> Моя интерпретация следующая:
> 
> > ШИМ+-
> 
> два провода: pwm 0-100% для перехода вперед, pwm другой сигнал для перехода назад
> 
> > ШИМ+ НАПРАВЛ.
> 
> 0-100% PWM и цифровой сигнал направления
> 
> > 0-50-100
> 
> 0% максимальной скорости PWM в одну сторону, 50% остановки PWM, 100% максимальной скорости PWM в другую сторону.

Yes, everything is right. Thank you !
It is strange that the controller created for robotics does not have industrial PWM, but instead only RC PWM

**Comment by active-game** [comment]
No news?

**Comment by Wetmelon** [comment]
> No news?

We have no plans to add this features at this time.
