### ISSUE TITLE
step/dir velocity tracking PLL and vel feedforward

### ISSUE THREAD

**Issue by madcowswe** [odriverobotics/ODrive#68]

**Comment by Wetmelon** [comment]
Per discussion in Discord:

* Set up TIM5 in Capture mode (free running timebase with time-stamping inputs)
* Timestamp each incoming step or PWM pulse  (#65)
* Determine velocity in motor_thread every cycle

**Comment by madcowswe** [comment]
See also: #110 about setpoint filtering.

**Comment by madcowswe** [comment]
merged to #110 .
