### ISSUE TITLE
Accessing anticog calibration data through ODrive tool

### ISSUE THREAD

**Issue by tbobrow1** [odriverobotics/ODrive#690]
Do you have any advice on how to modify the device firmware to enable access to the anticog calibration data through the ODrive Python tool? When I print the dictionary members in configuration.py, I see all of the Controller class members, including Anticogging_t, but the cogging_map member which holds the calibration data is omitted.

Will this require modifications to the Fibre library, or are there modifications that I can make on the firmware side to expose this data? I suspect this has something to do with the member being a data array, but I have not used the Fibre library before, and the documentation appears to be limited. Thanks for any tips that you can provide!

**Comment by Wetmelon** [comment]
The easiest way is to create a function which indexes into the cogmap, then you iterate that function.
