### ISSUE TITLE
What does firbe mean in the source code? 

### ISSUE THREAD

**Issue by zouzhe1** [odriverobotics/ODrive#692]
### Do you have any documents that introduce the file directory structure and design process? 
This can facilitate new developers to quickly and clearly understand the design of the whole OD.

**Comment by samuelsadok** [comment]
Fibre is the name for our custom communication framework between ODrive and the python library / `odrivetool`.
There's currently no good documentation about the directory structure and software architecture, you will have to navigate through the source code and comments in there.
