### ISSUE TITLE
dfu over can

### ISSUE THREAD

**Issue by SaumilShah66** [odriverobotics/ODrive#706]
**Is your feature request related to a problem? Please describe.**
System is in a closed box and my odrive is connected over can. Whenever I wan to update the firmware, I have to open the box, connect the USB and update the firmware.  

**Describe the solution you'd like**
If there is any way I can update the firmware over canbus, it solves my problem. I am not sure if it's doable or not though.

**Comment by Wetmelon** [comment]
Hi Saumil, this is a planned feature with high priority for Pro / S1, but may not make it to 3.6 for a long time, if ever.
