### ISSUE TITLE
USB bootloader

### ISSUE THREAD

**Issue by madcowswe** [odriverobotics/ODrive#72]
We should get the STM bootloader up and running, it's included in ROM in every STM.
[link](http://www.st.com/content/ccc/resource/technical/document/application_note/6a/17/92/02/58/98/45/0c/CD00264379.pdf/files/CD00264379.pdf/jcr:content/translations/en.CD00264379.pdf). Sample usage [link](https://github.com/rene-dev/stmbl/blob/692912ce1542985756f22b263f5fbe83530a347c/src/main.c#L72-L76)

If that has some major issues for some reason, here are some known implementations, in no particular order. Some might suck.

* Google for "stm usb bootloader", maybe there is something very easy to install.
* webdfu / webusb
* maple mini bootloader (used by VESC via ChibiOS, [link](https://github.com/vedderb/bldc/blob/master/ChibiOS_3.0.2/os/common/ports/ARMCMx/compilers/GCC/ld/STM32F103xE_maplemini_bootloader.ld)
* meseta's implementation: https://github.com/meseta

**Comment by madcowswe** [comment]
Notes by crinq:
in the long run you should use a custom post bootloader that checks fw crc and board revision
error -> jump to rom bootloader
ok -> jump to main fw
board revision is hardcoded in the post bootloader and in the fw info block
crc only: https://github.com/rene-dev/stmbl/tree/master/bootloader

**Comment by samuelsadok** [comment]
The actual jump to the system memory (where the bootloader lives) happens here:
https://github.com/rene-dev/stmbl/blob/master/bootloader/src/main.c#L65-L72
Apparently it uses the first flash sectors to CRCheck the rest and invoke the STM bootloader if necessary (however the code there is GPLv3 so we can't directly use it).

More low level documentation: [AN2606](http://www.st.com/content/ccc/resource/technical/document/application_note/b9/9b/16/3a/12/1e/40/0c/CD00167594.pdf/files/CD00167594.pdf)

(Note: from a security standpoint the STM bootloader seems kinda hopeless)

**Comment by madcowswe** [comment]
Adressed by #82
