### ISSUE TITLE
Delete a unclear or error or sth I don't konw class

### ISSUE THREAD

**Issue by Dyyt587** [odriverobotics/ODrive#728]
**Describe the bug**
Excuse me,may be it's foolish or simple,but I don"t know...
The problem is :
fibre-cpp/include/fibre/cpp_utils.hpp:979:30: warning: 'template<class _Category, class _Tp, class _Distance, class _Pointer, class _Reference> struct std::iterator' is deprecated [-Wdeprecated-declarations]
(ps: this class have never used in the project I guasing ,because I find nothing in the all sources by Ctrl+f )

**Solve function**
Just simply delate the class ,so I think may be it have something other  use ,if so ,please tell me ,thank you teaching.

**Comment by samuelsadok** [comment]
this is only a warning, not an error, so no action is required
