### ISSUE TITLE
Torque_msgs_ms rate from the gui is not setting the torque message for odrive s1

### ISSUE THREAD

**Issue by r4hul77** [odriverobotics/ODrive#739]
**Describe the bug**

**To Reproduce**
Steps and configuration necessary to reproduce the behavior.

**Expected behavior**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - odrivetool Version (`odrivetool --version`)

**Additional context**

**Comment by samuelsadok** [comment]
Does the rate setting work for other messages?

Can you copy&paste the diagnostics info from the GUI?

<img width="567" alt="image" src="https://github.com/odriverobotics/ODrive/assets/11528690/affc1c8d-368a-455b-80de-d0f2af79087f">

**Comment by r4hul77** [comment]
Yes the rate settings work for other messages, I'm reading the message through CAN and able to control the motor. I want all the messages at 10ms but it appears I'm missing torque messages always

**Comment by samuelsadok** [comment]
What's your firmware version? (see previous message to copy diagnostics info)

Do you have a way to log CAN messages? For instance on Linux you can install python-can (`pip3 install python-can`) and run `can_logger -i socketcan -c can0`. Could you grab 1 seconds worth of message log and share that?

**Comment by r4hul77** [comment]
The latest update fixed this issue if anyone is here with a similar problem
