### ISSUE TITLE
pyusb and pyserial

### ISSUE THREAD

**Issue by madcowswe** [odriverobotics/ODrive#92]
Give instructions on how to install this. Also import error should give helpful instruction on how to pip-install.

**Comment by samuelsadok** [comment]
This is addressed by allowing users to install the python tools via pip. The pip package includes pyusb and pyserial (and more) as dependencies.

**Comment by samuelsadok** [comment]
This is addressed by allowing users to install the python tools via pip. The pip package includes pyusb and pyserial (and more) as dependencies.
