### ISSUE TITLE
Stream-Based Protocol Issues

### ISSUE THREAD

**Issue by kylebme** [odriverobotics/ODrive#96]
The stream-based usb protocol is not working quite right. The python library throws an exception after 5 to 30 seconds of transferring data. It also throws an exception immediately when you try to connect, after it threw an exception before. Restarting the ODrive allows it to connect again, but it continues to disconnect and throw an exception after 5-30 seconds.

I've tested this on my Macbook, running MacOS 10.12.6. It might be an issue with the Python library, the operating system's driver, or with the ODrive Firmware. But most likely the Firmware.

I worked with Oskar to try to figure it out. Originally it wasn't throwing an exception, because the python ODrive library was waiting for 25 seconds to get a response. That is fixed so it now only waits 0.5s to timeout and throw an exception.

This is only an issue for stream-based protocol. This protocol is required on Mac. The packet-based protocol requires the built in driver to be released so that PyUSB/libusb can connect to it. This might be possible, and I'm looking into how to get this working. Having just one usb protocol would be better.

**Comment by samuelsadok** [comment]
Given that a lot of the protocol code has changed since Jan 2018, including the ODrive becoming a composite device rather than a simple CDC device, I suspect that this issue is no longer relevant. If there are still problems with the current `devel` branch, please feel free to reopen this or a new issue.
